<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATV0ifG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATV0ifG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATV0ifG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATV0ifG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerATV0ifG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ATV0ifG',
    'container.build_id' => '07750f32',
    'container.build_time' => 1708370035,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATV0ifG');
